/**
 * Generated by tsnapi — public API snapshot of `soft-expect`
 */
// #region Interfaces
export interface SoftExpect extends SoftExpectFn {
  once: (_: string, _: unknown, _: string, _?: SoftExpectContext) => boolean;
  rateLimited: (_: string, _: unknown, _: string, _?: SoftExpectContext) => boolean;
  sampled: (_: number, _: unknown, _: string, _?: SoftExpectContext) => boolean;
  devOnly: (_: unknown, _: string, _?: SoftExpectContext) => boolean;
  configure: (_: Partial<SoftExpectOptions>) => () => void;
  reset: () => void;
}
export interface SoftExpectFailure {
  message: string;
  context?: SoftExpectContext;
  key?: string;
  variant: SoftExpectVariant;
  timestamp: number;
}
export interface SoftExpectOptions {
  reporter: SoftExpectReporter;
  rateLimitMs: number;
  now: () => number;
  random: () => number;
}
// #endregion

// #region Types
export type SoftExpectContext = unknown;
export type SoftExpectFn = (_: unknown, _: string, _?: SoftExpectContext) => boolean;
export type SoftExpectReporter = (_: SoftExpectFailure) => void;
export type SoftExpectVariant = 'default' | 'once' | 'rateLimited' | 'sampled' | 'devOnly';
// #endregion

// #region Variables
export declare const configureSoftExpect: (options: Partial<SoftExpectOptions>) => () => void;
export declare const resetSoftExpect: () => void;
export declare const softExpect: SoftExpect;
// #endregion